version: "3"

services:
  server:
    container_name: minio-server
    image: minio/minio:RELEASE.2019-03-06T22-47-10Z
    restart: always
    volumes:
      - data:/data:delegated
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server /data

volumes:
  data:

networks:
  default:
    external:
      name: nginx-proxy
