version: "3"

services:
  client:
    container_name: ${COMPOSE_PROJECT_NAME}_client
    image: minio/mc
    entrypoint: mc config host add minio http://server:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    depends_on:
      - server
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
  server:
    container_name: ${COMPOSE_PROJECT_NAME}_server
    image: minio/minio:RELEASE.2020-02-27T00-23-05Z
    restart: always
    volumes:
      - data:/data
    expose:
      - 9000
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=9000
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server /data

volumes:
  data:

networks:
  default:
    external:
      name: nginx-proxy
